
package com.example.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CvCatalogImplService", targetNamespace = "http://service.example.com/", wsdlLocation = "http://localhost:9009/cvcatalogimpl/CvCatalog?wsdl")
public class CvCatalogImplService
    extends Service
{

    private final static URL CVCATALOGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CVCATALOGIMPLSERVICE_EXCEPTION;
    private final static QName CVCATALOGIMPLSERVICE_QNAME = new QName("http://service.example.com/", "CvCatalogImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9009/cvcatalogimpl/CvCatalog?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CVCATALOGIMPLSERVICE_WSDL_LOCATION = url;
        CVCATALOGIMPLSERVICE_EXCEPTION = e;
    }

    public CvCatalogImplService() {
        super(__getWsdlLocation(), CVCATALOGIMPLSERVICE_QNAME);
    }

    public CvCatalogImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CVCATALOGIMPLSERVICE_QNAME, features);
    }

    public CvCatalogImplService(URL wsdlLocation) {
        super(wsdlLocation, CVCATALOGIMPLSERVICE_QNAME);
    }

    public CvCatalogImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CVCATALOGIMPLSERVICE_QNAME, features);
    }

    public CvCatalogImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CvCatalogImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CvCatalogImpl
     */
    @WebEndpoint(name = "CvCatalogImplPort")
    public CvCatalogImpl getCvCatalogImplPort() {
        return super.getPort(new QName("http://service.example.com/", "CvCatalogImplPort"), CvCatalogImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CvCatalogImpl
     */
    @WebEndpoint(name = "CvCatalogImplPort")
    public CvCatalogImpl getCvCatalogImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.com/", "CvCatalogImplPort"), CvCatalogImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CVCATALOGIMPLSERVICE_EXCEPTION!= null) {
            throw CVCATALOGIMPLSERVICE_EXCEPTION;
        }
        return CVCATALOGIMPLSERVICE_WSDL_LOCATION;
    }

}
