
package com.example.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CvCatalogImpl", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CvCatalogImpl {


    /**
     * 
     * @param jobCategory
     * @return
     *     returns java.util.List<com.example.service.Cv>
     * @throws NoCvException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCv", targetNamespace = "http://service.example.com/", className = "com.example.service.GetCv")
    @ResponseWrapper(localName = "getCvResponse", targetNamespace = "http://service.example.com/", className = "com.example.service.GetCvResponse")
    @Action(input = "http://service.example.com/CvCatalogImpl/getCvRequest", output = "http://service.example.com/CvCatalogImpl/getCvResponse", fault = {
        @FaultAction(className = NoCvException_Exception.class, value = "http://service.example.com/CvCatalogImpl/getCv/Fault/NoCvException")
    })
    public List<Cv> getCv(
        @WebParam(name = "jobCategory", targetNamespace = "")
        String jobCategory)
        throws NoCvException_Exception
    ;

    /**
     * 
     * @param name
     * @param job
     * @param salary
     * @param age
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCv", targetNamespace = "http://service.example.com/", className = "com.example.service.AddCv")
    @ResponseWrapper(localName = "addCvResponse", targetNamespace = "http://service.example.com/", className = "com.example.service.AddCvResponse")
    @Action(input = "http://service.example.com/CvCatalogImpl/addCvRequest", output = "http://service.example.com/CvCatalogImpl/addCvResponse")
    public boolean addCv(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "job", targetNamespace = "")
        String job,
        @WebParam(name = "salary", targetNamespace = "")
        int salary,
        @WebParam(name = "age", targetNamespace = "")
        int age);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.service.Cv>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showAll", targetNamespace = "http://service.example.com/", className = "com.example.service.ShowAll")
    @ResponseWrapper(localName = "showAllResponse", targetNamespace = "http://service.example.com/", className = "com.example.service.ShowAllResponse")
    @Action(input = "http://service.example.com/CvCatalogImpl/showAllRequest", output = "http://service.example.com/CvCatalogImpl/showAllResponse")
    public List<Cv> showAll();

    /**
     * 
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCv", targetNamespace = "http://service.example.com/", className = "com.example.service.DeleteCv")
    @ResponseWrapper(localName = "deleteCvResponse", targetNamespace = "http://service.example.com/", className = "com.example.service.DeleteCvResponse")
    @Action(input = "http://service.example.com/CvCatalogImpl/deleteCvRequest", output = "http://service.example.com/CvCatalogImpl/deleteCvResponse")
    public boolean deleteCv(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
