
package com.example.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoCvException", targetNamespace = "http://service.example.com/")
public class NoCvException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoCvException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoCvException_Exception(String message, NoCvException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoCvException_Exception(String message, NoCvException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.service.NoCvException
     */
    public NoCvException getFaultInfo() {
        return faultInfo;
    }

}
